from pyfcm import FCMnotification
push_service = FCMNotification(api_key="AAAA8wzII3Y:APA91bGdO8pfuMOYHqQI-ZGfPlRUFycciPMw-ROOTZI5x6llYdM_U5sYJcSlyAF2LUq6aMJcs3VjoJfeCOdxHPCD5hUgImPWpYZAlxKcx1ENtsJb3sjfv3zkjdQU6B1qDD9Uj4GCQK4Up8aPcgSijaqapBb-NVFMaA")

